name: Integration Tests Reporter

on:
  workflow_run:
    workflows: ["Integration Tests"]
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        uses: potiuk/get-workflow-origin@v1_6
        id: workflow-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Report status
        if: steps.workflow-run-info.outputs.pull_request_number
        uses: LouisBrunner/checks-action@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Chronicle Integration Tests
          status: completed
          conclusion: ${{ github.event.workflow_run.conclusion }}
          sha: ${{ steps.workflow-run-info.outputs.pull_request_head_sha }}
          details_url: ${{ github.event.workflow_run.html_url }}
          output: |
            {"summary": "Integration tests ${{ github.event.workflow_run.conclusion == 'success' && 'passed!' || 'failed!' }}. [View logs](${{ github.event.workflow_run.html_url }})"}